apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contextos.fullname" . }}
  labels: {{ include "contextos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "contextos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "contextos.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name:  {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
