# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbus.proto\x12\x10\x63ontextos.bus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n\x0bMemoryEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12/\n\x04kind\x18\x02 \x01(\x0e\x32!.contextos.bus.v1.MemoryEventKind\x12\x11\n\tmemory_id\x18\x03 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x04 \x01(\t\x12\r\n\x05scope\x18\x05 \x01(\t\x12;\n\x07payload\x18\x06 \x03(\x0b\x32*.contextos.bus.v1.MemoryEvent.PayloadEntry\x12/\n\x0boccurred_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x13PublishEventRequest\x12,\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1d.contextos.bus.v1.MemoryEvent\"4\n\x14PublishEventResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\"r\n\x10SubscribeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x36\n\x0b\x65vent_kinds\x18\x02 \x03(\x0e\x32!.contextos.bus.v1.MemoryEventKind\x12\x14\n\x0cscope_filter\x18\x03 \x01(\t*\xc6\x01\n\x0fMemoryEventKind\x12!\n\x1dMEMORY_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x12\n\x0eMEMORY_CREATED\x10\x01\x12\x12\n\x0eMEMORY_UPDATED\x10\x02\x12\x13\n\x0fMEMORY_PROMOTED\x10\x03\x12\x13\n\x0fMEMORY_ARCHIVED\x10\x04\x12\x10\n\x0cSCOPE_SHARED\x10\x05\x12\x14\n\x10\x41GENT_SUBSCRIBED\x10\x06\x12\x16\n\x12\x41GENT_UNSUBSCRIBED\x10\x07\x32\xc3\x01\n\x10MemoryBusService\x12]\n\x0cPublishEvent\x12%.contextos.bus.v1.PublishEventRequest\x1a&.contextos.bus.v1.PublishEventResponse\x12P\n\tSubscribe\x12\".contextos.bus.v1.SubscribeRequest\x1a\x1d.contextos.bus.v1.MemoryEvent0\x01\x42\x17\n\x13io.contextos.bus.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.contextos.bus.v1P\001'
  _globals['_MEMORYEVENT_PAYLOADENTRY']._loaded_options = None
  _globals['_MEMORYEVENT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_MEMORYEVENTKIND']._serialized_start=597
  _globals['_MEMORYEVENTKIND']._serialized_end=795
  _globals['_MEMORYEVENT']._serialized_start=65
  _globals['_MEMORYEVENT']._serialized_end=355
  _globals['_MEMORYEVENT_PAYLOADENTRY']._serialized_start=309
  _globals['_MEMORYEVENT_PAYLOADENTRY']._serialized_end=355
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=357
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=424
  _globals['_PUBLISHEVENTRESPONSE']._serialized_start=426
  _globals['_PUBLISHEVENTRESPONSE']._serialized_end=478
  _globals['_SUBSCRIBEREQUEST']._serialized_start=480
  _globals['_SUBSCRIBEREQUEST']._serialized_end=594
  _globals['_MEMORYBUSSERVICE']._serialized_start=798
  _globals['_MEMORYBUSSERVICE']._serialized_end=993
# @@protoc_insertion_point(module_scope)
