# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bus_pb2 as bus__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryBusServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishEvent = channel.unary_unary(
                '/contextos.bus.v1.MemoryBusService/PublishEvent',
                request_serializer=bus__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=bus__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/contextos.bus.v1.MemoryBusService/Subscribe',
                request_serializer=bus__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=bus__pb2.MemoryEvent.FromString,
                _registered_method=True)


class MemoryBusServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryBusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=bus__pb2.PublishEventRequest.FromString,
                    response_serializer=bus__pb2.PublishEventResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=bus__pb2.SubscribeRequest.FromString,
                    response_serializer=bus__pb2.MemoryEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextos.bus.v1.MemoryBusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextos.bus.v1.MemoryBusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryBusService(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.bus.v1.MemoryBusService/PublishEvent',
            bus__pb2.PublishEventRequest.SerializeToString,
            bus__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/contextos.bus.v1.MemoryBusService/Subscribe',
            bus__pb2.SubscribeRequest.SerializeToString,
            bus__pb2.MemoryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
