# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import context_pb2 as context__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in context_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextSchedulerServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleContext = channel.unary_unary(
                '/contextos.context.v1.ContextSchedulerService/ScheduleContext',
                request_serializer=context__pb2.ScheduleContextRequest.SerializeToString,
                response_deserializer=context__pb2.ScheduleContextResponse.FromString,
                _registered_method=True)
        self.GetContextWindow = channel.unary_unary(
                '/contextos.context.v1.ContextSchedulerService/GetContextWindow',
                request_serializer=context__pb2.GetContextWindowRequest.SerializeToString,
                response_deserializer=context__pb2.ContextWindow.FromString,
                _registered_method=True)
        self.UpdateContext = channel.unary_unary(
                '/contextos.context.v1.ContextSchedulerService/UpdateContext',
                request_serializer=context__pb2.UpdateContextRequest.SerializeToString,
                response_deserializer=context__pb2.UpdateContextResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/contextos.context.v1.ContextSchedulerService/CloseSession',
                request_serializer=context__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Evict = channel.unary_unary(
                '/contextos.context.v1.ContextSchedulerService/Evict',
                request_serializer=context__pb2.EvictRequest.SerializeToString,
                response_deserializer=context__pb2.EvictResponse.FromString,
                _registered_method=True)


class ContextSchedulerServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def ScheduleContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContextWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextSchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScheduleContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleContext,
                    request_deserializer=context__pb2.ScheduleContextRequest.FromString,
                    response_serializer=context__pb2.ScheduleContextResponse.SerializeToString,
            ),
            'GetContextWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContextWindow,
                    request_deserializer=context__pb2.GetContextWindowRequest.FromString,
                    response_serializer=context__pb2.ContextWindow.SerializeToString,
            ),
            'UpdateContext': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContext,
                    request_deserializer=context__pb2.UpdateContextRequest.FromString,
                    response_serializer=context__pb2.UpdateContextResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=context__pb2.CloseSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Evict': grpc.unary_unary_rpc_method_handler(
                    servicer.Evict,
                    request_deserializer=context__pb2.EvictRequest.FromString,
                    response_serializer=context__pb2.EvictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextos.context.v1.ContextSchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextos.context.v1.ContextSchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextSchedulerService(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def ScheduleContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.context.v1.ContextSchedulerService/ScheduleContext',
            context__pb2.ScheduleContextRequest.SerializeToString,
            context__pb2.ScheduleContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContextWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.context.v1.ContextSchedulerService/GetContextWindow',
            context__pb2.GetContextWindowRequest.SerializeToString,
            context__pb2.ContextWindow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.context.v1.ContextSchedulerService/UpdateContext',
            context__pb2.UpdateContextRequest.SerializeToString,
            context__pb2.UpdateContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.context.v1.ContextSchedulerService/CloseSession',
            context__pb2.CloseSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.context.v1.ContextSchedulerService/Evict',
            context__pb2.EvictRequest.SerializeToString,
            context__pb2.EvictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
