# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import indexer_pb2 as indexer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in indexer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexerServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IndexRepository = channel.unary_unary(
                '/contextos.indexer.v1.IndexerService/IndexRepository',
                request_serializer=indexer__pb2.IndexRepositoryRequest.SerializeToString,
                response_deserializer=indexer__pb2.IndexRepositoryResponse.FromString,
                _registered_method=True)
        self.GetSymbol = channel.unary_unary(
                '/contextos.indexer.v1.IndexerService/GetSymbol',
                request_serializer=indexer__pb2.GetSymbolRequest.SerializeToString,
                response_deserializer=indexer__pb2.GetSymbolResponse.FromString,
                _registered_method=True)
        self.QuerySymbols = channel.unary_unary(
                '/contextos.indexer.v1.IndexerService/QuerySymbols',
                request_serializer=indexer__pb2.QuerySymbolsRequest.SerializeToString,
                response_deserializer=indexer__pb2.QuerySymbolsResponse.FromString,
                _registered_method=True)
        self.GetCommitDiff = channel.unary_unary(
                '/contextos.indexer.v1.IndexerService/GetCommitDiff',
                request_serializer=indexer__pb2.GetCommitDiffRequest.SerializeToString,
                response_deserializer=indexer__pb2.GetCommitDiffResponse.FromString,
                _registered_method=True)
        self.QueryFunctionDeltas = channel.unary_unary(
                '/contextos.indexer.v1.IndexerService/QueryFunctionDeltas',
                request_serializer=indexer__pb2.QueryFunctionDeltasRequest.SerializeToString,
                response_deserializer=indexer__pb2.QueryFunctionDeltasResponse.FromString,
                _registered_method=True)


class IndexerServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def IndexRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommitDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFunctionDeltas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IndexRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexRepository,
                    request_deserializer=indexer__pb2.IndexRepositoryRequest.FromString,
                    response_serializer=indexer__pb2.IndexRepositoryResponse.SerializeToString,
            ),
            'GetSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbol,
                    request_deserializer=indexer__pb2.GetSymbolRequest.FromString,
                    response_serializer=indexer__pb2.GetSymbolResponse.SerializeToString,
            ),
            'QuerySymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySymbols,
                    request_deserializer=indexer__pb2.QuerySymbolsRequest.FromString,
                    response_serializer=indexer__pb2.QuerySymbolsResponse.SerializeToString,
            ),
            'GetCommitDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommitDiff,
                    request_deserializer=indexer__pb2.GetCommitDiffRequest.FromString,
                    response_serializer=indexer__pb2.GetCommitDiffResponse.SerializeToString,
            ),
            'QueryFunctionDeltas': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFunctionDeltas,
                    request_deserializer=indexer__pb2.QueryFunctionDeltasRequest.FromString,
                    response_serializer=indexer__pb2.QueryFunctionDeltasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextos.indexer.v1.IndexerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextos.indexer.v1.IndexerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndexerService(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def IndexRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.indexer.v1.IndexerService/IndexRepository',
            indexer__pb2.IndexRepositoryRequest.SerializeToString,
            indexer__pb2.IndexRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.indexer.v1.IndexerService/GetSymbol',
            indexer__pb2.GetSymbolRequest.SerializeToString,
            indexer__pb2.GetSymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.indexer.v1.IndexerService/QuerySymbols',
            indexer__pb2.QuerySymbolsRequest.SerializeToString,
            indexer__pb2.QuerySymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommitDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.indexer.v1.IndexerService/GetCommitDiff',
            indexer__pb2.GetCommitDiffRequest.SerializeToString,
            indexer__pb2.GetCommitDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryFunctionDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.indexer.v1.IndexerService/QueryFunctionDeltas',
            indexer__pb2.QueryFunctionDeltasRequest.SerializeToString,
            indexer__pb2.QueryFunctionDeltasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
