# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'optimizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foptimizer.proto\x12\x16\x63ontextos.optimizer.v1\x1a\x1bgoogle/protobuf/empty.proto\"a\n\x13PromotionSuggestion\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x13\n\x0btarget_tier\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"x\n\x11\x43ompressionResult\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x12\n\ncompressed\x18\x02 \x01(\x08\x12\x15\n\rbefore_tokens\x18\x03 \x01(\x05\x12\x14\n\x0c\x61\x66ter_tokens\x18\x04 \x01(\x05\x12\x0f\n\x07summary\x18\x05 \x01(\t\"A\n\x1eGetPromotionSuggestionsRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"c\n\x1fGetPromotionSuggestionsResponse\x12@\n\x0bsuggestions\x18\x01 \x03(\x0b\x32+.contextos.optimizer.v1.PromotionSuggestion\"@\n\x19TriggerCompressionRequest\x12\x11\n\tmemory_id\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t\"W\n\x1aTriggerCompressionResponse\x12\x39\n\x06result\x18\x01 \x01(\x0b\x32).contextos.optimizer.v1.CompressionResult2\x9c\x02\n\x10OptimizerService\x12\x8a\x01\n\x17GetPromotionSuggestions\x12\x36.contextos.optimizer.v1.GetPromotionSuggestionsRequest\x1a\x37.contextos.optimizer.v1.GetPromotionSuggestionsResponse\x12{\n\x12TriggerCompression\x12\x31.contextos.optimizer.v1.TriggerCompressionRequest\x1a\x32.contextos.optimizer.v1.TriggerCompressionResponseB\x1d\n\x19io.contextos.optimizer.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031io.contextos.optimizer.v1P\001'
  _globals['_PROMOTIONSUGGESTION']._serialized_start=72
  _globals['_PROMOTIONSUGGESTION']._serialized_end=169
  _globals['_COMPRESSIONRESULT']._serialized_start=171
  _globals['_COMPRESSIONRESULT']._serialized_end=291
  _globals['_GETPROMOTIONSUGGESTIONSREQUEST']._serialized_start=293
  _globals['_GETPROMOTIONSUGGESTIONSREQUEST']._serialized_end=358
  _globals['_GETPROMOTIONSUGGESTIONSRESPONSE']._serialized_start=360
  _globals['_GETPROMOTIONSUGGESTIONSRESPONSE']._serialized_end=459
  _globals['_TRIGGERCOMPRESSIONREQUEST']._serialized_start=461
  _globals['_TRIGGERCOMPRESSIONREQUEST']._serialized_end=525
  _globals['_TRIGGERCOMPRESSIONRESPONSE']._serialized_start=527
  _globals['_TRIGGERCOMPRESSIONRESPONSE']._serialized_end=614
  _globals['_OPTIMIZERSERVICE']._serialized_start=617
  _globals['_OPTIMIZERSERVICE']._serialized_end=901
# @@protoc_insertion_point(module_scope)
