# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import policy_pb2 as policy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckPermission = channel.unary_unary(
                '/contextos.policy.v1.PolicyService/CheckPermission',
                request_serializer=policy__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=policy__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/contextos.policy.v1.PolicyService/CreateRole',
                request_serializer=policy__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=policy__pb2.CreateRoleResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/contextos.policy.v1.PolicyService/AssignRole',
                request_serializer=policy__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RecordAuditEvent = channel.unary_unary(
                '/contextos.policy.v1.PolicyService/RecordAuditEvent',
                request_serializer=policy__pb2.AuditEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/contextos.policy.v1.PolicyService/ListAuditEvents',
                request_serializer=policy__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=policy__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)
        self.StreamAuditEvents = channel.unary_stream(
                '/contextos.policy.v1.PolicyService/StreamAuditEvents',
                request_serializer=policy__pb2.StreamAuditRequest.SerializeToString,
                response_deserializer=policy__pb2.AuditEvent.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    def CheckPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordAuditEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAuditEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=policy__pb2.CheckPermissionRequest.FromString,
                    response_serializer=policy__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=policy__pb2.CreateRoleRequest.FromString,
                    response_serializer=policy__pb2.CreateRoleResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=policy__pb2.AssignRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RecordAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAuditEvent,
                    request_deserializer=policy__pb2.AuditEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=policy__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=policy__pb2.ListAuditEventsResponse.SerializeToString,
            ),
            'StreamAuditEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAuditEvents,
                    request_deserializer=policy__pb2.StreamAuditRequest.FromString,
                    response_serializer=policy__pb2.AuditEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextos.policy.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextos.policy.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """─── Service ──────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.policy.v1.PolicyService/CheckPermission',
            policy__pb2.CheckPermissionRequest.SerializeToString,
            policy__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.policy.v1.PolicyService/CreateRole',
            policy__pb2.CreateRoleRequest.SerializeToString,
            policy__pb2.CreateRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.policy.v1.PolicyService/AssignRole',
            policy__pb2.AssignRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.policy.v1.PolicyService/RecordAuditEvent',
            policy__pb2.AuditEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextos.policy.v1.PolicyService/ListAuditEvents',
            policy__pb2.ListAuditEventsRequest.SerializeToString,
            policy__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/contextos.policy.v1.PolicyService/StreamAuditEvents',
            policy__pb2.StreamAuditRequest.SerializeToString,
            policy__pb2.AuditEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
