"""
ContextOS Python SDK — gRPC client.

Usage::

    from contextos import ContextOSClient, MemoryTier, Scope

    client = ContextOSClient("localhost:50051")
    entry_id = client.memory.store(
        agent_id="agent-001",  # human-readable IDs are auto-converted to UUIDs
        content="The refactor moves auth logic to middleware.py",
        tier=MemoryTier.L2_TASK,
        scope=Scope.TEAM,
    )
    entry = client.memory.get(entry_id)

Note: This client wraps the raw gRPC stubs generated by grpcio-tools.
Run `make proto-python` from the repo root to regenerate the stubs.
"""

from __future__ import annotations

import uuid
import grpc
from typing import Optional


# ── UUID coercion ─────────────────────────────────────────────────────────────

_CONTEXTOS_NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")  # UUID namespace

def _coerce_uuid(value: str) -> str:
    """Accept either a valid UUID string or any human-readable ID.

    Human-readable strings (e.g. ``"agent-001"``) are deterministically mapped
    to a UUID5 so the same string always produces the same UUID.  Valid UUID
    strings pass through unchanged.
    """
    try:
        return str(uuid.UUID(value))
    except ValueError:
        return str(uuid.uuid5(_CONTEXTOS_NS, value))

from .types import (
    MemoryEntry, MemoryTier, Scope,
    SymbolNode, SymbolKind,
    CommitDiff,
    MemoryEvent, MemoryEventKind,
    ContextWindow, EvictionPolicy,
)


class _MemoryClient:
    """High-level wrapper around the MemoryService gRPC stub."""

    def __init__(self, channel: grpc.Channel) -> None:
        self._channel = channel
        # Stub is imported lazily so the SDK can be imported without generated code
        self._stub: Optional[object] = None

    def _get_stub(self):
        if self._stub is None:
            try:
                from contextos.proto import memory_pb2_grpc  # type: ignore
                self._stub = memory_pb2_grpc.MemoryServiceStub(self._channel)
            except ImportError as e:
                raise RuntimeError(
                    "Proto stubs not found. Run `make proto-python` to generate them."
                ) from e
        return self._stub

    def store(
        self,
        agent_id: str,
        content: str,
        tier: MemoryTier = MemoryTier.L1_SESSION,
        scope: Scope = Scope.PRIVATE,
        tags: list[str] | None = None,
        metadata: dict[str, str] | None = None,
    ) -> str:
        """Store a memory entry and return its ID."""
        from contextos.proto import memory_pb2  # type: ignore
        req = memory_pb2.StoreMemoryRequest(
            agent_id = _coerce_uuid(agent_id),
            content  = content,
            tier     = tier.value,
            scope    = scope.value,
            tags     = tags or [],
        )
        if metadata:
            req.metadata.update(metadata)
        resp = self._get_stub().StoreMemory(req)
        return resp.id

    def get(self, memory_id: str) -> Optional[MemoryEntry]:
        """Retrieve a memory entry by ID, or None if not found."""
        from contextos.proto import memory_pb2  # type: ignore
        req  = memory_pb2.GetMemoryRequest(id=memory_id)
        resp = self._get_stub().GetMemory(req)
        if not resp.HasField("entry"):
            return None
        e = resp.entry
        return MemoryEntry(
            id      = e.id,
            agent_id= e.agent_id,
            content = e.content,
            tier    = MemoryTier(e.tier),
            scope   = Scope(e.scope),
            score   = e.score,
            tags    = list(e.tags),
            metadata= dict(e.metadata),
        )

    def search(
        self,
        agent_id: str,
        query: str,
        top_k: int = 10,
        scope: Scope | None = None,
    ) -> list[MemoryEntry]:
        """Semantic search across memories.

        ``scope=None`` (default) searches across all scopes.
        Pass a specific :class:`Scope` to restrict results.
        """
        from contextos.proto import memory_pb2  # type: ignore
        req  = memory_pb2.SearchMemoryRequest(
            agent_id = _coerce_uuid(agent_id),
            query    = query,
            top_k    = top_k,
            scope    = scope.value if scope is not None else 0,
        )
        resp = self._get_stub().SearchMemory(req)
        return [
            MemoryEntry(
                id      = e.id,
                agent_id= e.agent_id,
                content = e.content,
                tier    = MemoryTier(e.tier),
                scope   = Scope(e.scope),
                score   = e.score,
            )
            for e in resp.results
        ]

    def delete(self, memory_id: str) -> bool:
        from contextos.proto import memory_pb2  # type: ignore
        resp = self._get_stub().DeleteMemory(memory_pb2.DeleteMemoryRequest(id=memory_id))
        return resp.ok


class _IndexerClient:
    def __init__(self, channel: grpc.Channel) -> None:
        self._channel = channel

    def _get_stub(self):
        from contextos.proto import indexer_pb2_grpc  # type: ignore
        return indexer_pb2_grpc.IndexerServiceStub(self._channel)

    def index_repo(self, repo_id: str, local_path: str, languages: list[str], incremental: bool = False) -> dict:
        from contextos.proto import indexer_pb2  # type: ignore
        req  = indexer_pb2.IndexRepositoryRequest(
            repo_id    = repo_id,
            local_path = local_path,
            languages  = languages,
            incremental= incremental,
        )
        resp = self._get_stub().IndexRepository(req)
        return {"ok": resp.ok, "symbols_added": resp.symbols_added, "duration_ms": resp.duration_ms}

    def query_symbols(self, repo_id: str, query: str, top_k: int = 10) -> list[SymbolNode]:
        from contextos.proto import indexer_pb2  # type: ignore
        req  = indexer_pb2.QuerySymbolsRequest(repo_id=repo_id, query=query, top_k=top_k)
        resp = self._get_stub().QuerySymbols(req)
        return [
            SymbolNode(
                id             = s.id,
                repo_id        = s.repo_id,
                file_path      = s.file_path,
                name           = s.name,
                qualified_name = s.qualified_name,
                kind           = SymbolKind(s.kind),
                start_line     = s.start_line,
                end_line       = s.end_line,
            )
            for s in resp.results
        ]


class ContextOSClient:
    """
    Top-level ContextOS client that provides access to all subsystems:

    - ``client.memory``    — MemoryService
    - ``client.indexer``   — IndexerService
    """

    def __init__(self, address: str = "localhost:50051", use_tls: bool = False) -> None:
        if use_tls:
            self._channel = grpc.secure_channel(address, grpc.ssl_channel_credentials())
        else:
            self._channel = grpc.insecure_channel(address)

        self.memory  = _MemoryClient(self._channel)
        self.indexer = _IndexerClient(self._channel)

    def close(self) -> None:
        self._channel.close()

    def __enter__(self) -> "ContextOSClient":
        return self

    def __exit__(self, *args) -> None:
        self.close()
